# File: motor_interfaces/srv/SetTargetPosition.srv
#
# motor_interfaces: ROS 2 package containing custom messages, services and actions for the control of a BLDC motor using SimpleFOC and MicroROS
# SetTargetPosition.msg: Custom service definition for changing the position of the motor w.r.t the hall effect sensor beneath the motor
#
# Description:
# This service defines the interface for a request-response interaction for changing position of the motor and holding it.
# Note that the motor must be in the `Position Control (closed loop)` operating mode for this service to function.
# The service will respond with a code described below according to the system state and effect.
#
# Request:
# float64 target   # The target position in radians from [0, 2pi)
#
# Response:
# uint8 result  # Result of the operation. See table below for details
#
# Code | Description
# -----+--------------------------------------------------------------------------------------
#  0   | Operation success; target position set
#  1   | Operation failed - unspecified error
#  2   | Operation failed - FOC controller is not in the Position Control (closed loop) state

float64 target
---
uint8 result